const mongoose = require('mongoose');
const Schema = mongoose.Schema;

var UComportementales = Schema({
    souscategorie:String,
    Illustrationinnovation:String,
    Illustrationinnovation2:String,
    Illustrationinnovation3:String,
    Illustrationinnovation4:String,
    Illustrationinnovation5:String,
    Illustrationinnovation6:String,
    Illustrationinnovation7:String,
    Illustrationinnovation8:String,
    Illustrationinnovation9:String,
    Illustrationinnovation10:String,
    Illustrationinnovation11:String,
    Illustrationinnovation12:String,
    Illustrationinnovation13:String,
    IllustrationAgilit:String,
    IllustrationAgilit2:String,
    IllustrationAgilit3:String,
    IllustrationAgilit4:String,
    IllustrationAgilit5:String,
    IllustrationAgilit6:String,
    IllustrationAgilit7:String,
    IllustrationAgilit8:String,
    IllustrationAgilit9:String,
    IllustrationAgilit10:String,
    IllustrationAgilit11:String,
    IllustrationAgilit12:String,
    IllustrationAgilit13:String,
    IllustrationForceCollectif:String,
    IllustrationForceCollectif2:String,
    IllustrationForceCollectif3:String,
    IllustrationForceCollectif4:String,
    IllustrationForceCollectif5:String,
    IllustrationForceCollectif6:String,
    IllustrationForceCollectif7:String,
    IllustrationForceCollectif8:String,
    IllustrationForceCollectif9:String,
    IllustrationForceCollectif10:String,
    IllustrationForceCollectif11:String,
    IllustrationForceCollectif12:String,
    IllustrationForceCollectif13:String,
    IllustrationRespectEngagement:String,
    IllustrationRespectEngagement2:String,
    IllustrationRespectEngagement3:String,
    IllustrationRespectEngagement4:String,
    IllustrationRespectEngagement5:String,
    IllustrationRespectEngagement6:String,
    IllustrationRespectEngagement7:String,
    IllustrationRespectEngagement8:String,
    IllustrationRespectEngagement9:String,
    IllustrationRespectEngagement10:String,
    IllustrationRespectEngagement11:String,
    IllustrationRespectEngagement12:String,
    IllustrationRespectEngagement13:String,
   
});

module.exports =  UComportementales = mongoose.model('uComportementales',UComportementales);
