const mongoose = require('mongoose');
const Schema = mongoose.Schema;

var Umanagerials = Schema({
    souscategorie:String,
    IllustrationOrientationstrategique:String,
    IllustrationOrientationstrategique2:String,
    IllustrationOrientationstrategique3:String,
    IllustrationOrientationstrategique4:String,
    IllustrationOrientationstrategique5:String,
    IllustrationOrientationstrategique6:String,
    IllustrationOrientationstrategique7:String,
    IllustrationOrientationstrategique8:String,
    IllustrationOrientationstrategique9:String,
    IllustrationOrientationstrategique10:String,
    IllustrationOrientationstrategique11:String,
    IllustrationOrientationstrategique12:String,
    IllustrationOrientationstrategique13:String,
    IllustrationSensdesaffaires:String,
    IllustrationSensdesaffaires2:String,
    IllustrationSensdesaffaires3:String,
    IllustrationSensdesaffaires4:String,
    IllustrationSensdesaffaires5:String,
    IllustrationSensdesaffaires6:String,
    IllustrationSensdesaffaires7:String,
    IllustrationSensdesaffaires8:String,
    IllustrationSensdesaffaires9:String,
    IllustrationSensdesaffaires10:String,
    IllustrationSensdesaffaires11:String,
    IllustrationSensdesaffaires12:String,
    IllustrationSensdesaffaires13:String,
    IllustrationLeadership:String,
    IllustrationLeadership2:String,
    IllustrationLeadership3:String,
    IllustrationLeadership4:String,
    IllustrationLeadership5:String,
    IllustrationLeadership6:String,
    IllustrationLeadership7:String,
    IllustrationLeadership8:String,
    IllustrationLeadership9:String,
    IllustrationLeadership10:String,
    IllustrationLeadership11:String,
    IllustrationLeadership12:String,
    IllustrationLeadership13:String,
    IllustrationGestionOperationnelle:String,
    IllustrationGestionOperationnelle2:String,
    IllustrationGestionOperationnelle3:String,
    IllustrationGestionOperationnelle4:String,
    IllustrationGestionOperationnelle5:String,
    IllustrationGestionOperationnelle6:String,
    IllustrationGestionOperationnelle7:String,
    IllustrationGestionOperationnelle8:String,
    IllustrationGestionOperationnelle9:String,
    IllustrationGestionOperationnelle10:String,
    IllustrationGestionOperationnelle11:String,
    IllustrationGestionOperationnelle12:String,
    IllustrationGestionOperationnelle13:String,
    IllustrationGestionEquipe:String,
    IllustrationGestionEquipe2:String,
    IllustrationGestionEquipe3:String,
    IllustrationGestionEquipe4:String,
    IllustrationGestionEquipe5:String,
    IllustrationGestionEquipe6:String,
    IllustrationGestionEquipe7:String,
    IllustrationGestionEquipe8:String,
    IllustrationGestionEquipe9:String,
    IllustrationGestionEquipe10:String,
    IllustrationGestionEquipe11:String,
    IllustrationGestionEquipe12:String,
    IllustrationGestionEquipe13:String,
   
});

module.exports =  Umanagerials = mongoose.model('umanagerials',Umanagerials);
